### PR TITLE
Switch to redux-saga

### PR DESCRIPTION
**Pull request by benderr**

### CODE REVIEW

**Comment by Stanko** [comment]
Thanks @benderr we will merge this for sure. I'm just thinking how to implement a way of choosing between thunk and saga.

@oliverdore-work @nemanjawork @edwintoh-work what do you guys think?

**Comment by edwintoh-work** [comment]
Hmm yeah, I didn't know whether we should have redux-saga as the default or thunk as the default and that kind of paralyzed me doing a PR for this until now. I think this is up to you though!

**Comment by Evanht** [comment]
Hey guys, when are you panning on adding redux-saga?

**Comment by Stanko** [comment]
@Evanht there is on going discussion should we, or should we not. ATM things are moving slowly, so not sure when we are going to merge this fine PR.

**Comment by Stanko** [comment]
Sagas coming with the version, thanks benderr!

**Pull request closed without merging**
